### ISSUE TITLE
pool's componentPools.

### ISSUE THREAD

**Issue by marshal-it** [JuDelCo/Entitas-Cpp#5]
entity = EntityPtr(new Entity(&mComponentPools), [](void* entity)
		{
			(static_cast<Entity*>(entity)->OnEntityReleased(static_cast<Entity*>(entity)));
		});

when new pool，the mComponentPools is null, so use pool to create entity, no componetpool to entity,  entity add componet by self, but why entity's component ref  not pass to pool's mComponentPools, because entity's component not need pass to pool's mComponentPools, the mComponentPools will always null. so this a problem?

**Comment by marshal-it** [comment]
pool‘s componentpools not use to save component ref from entity, only pool provide component to entity when entity need ??

**Comment by JuDelCo** [comment]
In order to use entities, you should create first a `Pool`.	
`mComponentPools` is created before the pool constructor automatically, so it can't be null.

Example:
```cpp
auto pool = new Pool();
auto e = pool->CreateEntity();
```

See the README for more info:
https://github.com/JuDelCo/Entitas-Cpp/blob/master/README.md
