### ISSUE TITLE
use_count > 1 error

### ISSUE THREAD

**Issue by Wow-Coder-Man** [JuDelCo/Entitas-Cpp#7]
EntityPtr createdEntity = pool->CreateEntity();
	pool->ClearGroups();
	pool->DestroyAllEntities();

this code will occur an runtime_error. use_count issues

**Comment by JuDelCo** [comment]
I'm aware the code has some memory bugs (see this repo issues), I currently don't have the time & interest to fix them, but feel free to fork the code and fix them !  (I know, C++ is hard 😬 )

**Comment by JuDelCo** [comment]
Hi, if you are using a shared_ptr, you should release the pointer then using .reset() if you want to destroy all entities.

```cpp
	EntityPtr createdEntity = pool->CreateEntity();
	createdEntity.reset();
	pool->ClearGroups();
	pool->DestroyAllEntities();
```
