### ISSUE TITLE
is the order of the entities matching in a group guaranteed?

### ISSUE THREAD

**Issue by grimaldini** [JuDelCo/Entitas-Cpp#8]
I am adding new entities with a given component and in a system, I'm iterating over the existing entities that have that component using a group matcher. Are the entities returned with the getEntity function guaranteed to be provided in the same order in which they given assigned given component?

**Comment by JuDelCo** [comment]
If the group instance/reference is the same, yes**. If there are already entities matching the group filter when it is created, no.

** Entities will be cached iterating all entities in the pool and filtering them using the matcher of the group, and that is *not* sorted in the same order they were assigned their components.

To make sure the entities are sorted the way you want, make sure the group is created before adding any entities that match that group filter, so they will be sorted in the same order in which they are given their components. Also make sure you keep a reference to that group alive so it doesn't get destroyed automatically.
