### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kobato0328** [JuDelCo/Entitas-Cpp#9]
Hi, When i compiled it,  some compile error about std::funtion,
and I add ///#include functional, in Delegate.hpp , it works well.
maybe forgot it or the version of compiler diff?

**Comment by JuDelCo** [comment]
Hi !, apparently different compilers have different implementations of the header files. So some may include the functional header file by another header file used in that file (mutex, list, vector o memory).

More info: https://stackoverflow.com/a/42285145

That is what seems to have happened to me, I used Clang to create this project and it seems that with that compiler it may be the case that functional is being included in another header file.

I just commited a fix for this, thanks for your feedback

https://github.com/JuDelCo/Entitas-Cpp/commit/4dd4093fd2759839f6a83a85db3562a83e363c53
